# List Exercises 03/03/2018

## 1. Sum the Numbers

In [1]:
numbers = [1,2,4,6,2,3,6,-5,-7]
print (sum(numbers))

12


## 2. Largest Number

In [2]:
print (max(numbers))

6


## 3. Smallest Number

In [3]:
print(min(numbers))

-7


## 4. Even Numbers

In [4]:
for number in numbers:
    if number%2==0:
        print (number)

2
4
6
2
6


## 5. Positive Numbers

In [5]:
for number in numbers:
    if number > 0:
        print (number)

1
2
4
6
2
3
6


## 6. Positive Numbers 2

In [6]:
new_nums = list(filter(lambda x: x >0, numbers))
print("Positive numbers in the list: ",new_nums)

Positive numbers in the list:  [1, 2, 4, 6, 2, 3, 6]


## 7. Multiply a list

In [7]:
factor = 3
numbers[:] = [x * factor for x in numbers]
print(numbers)

[3, 6, 12, 18, 6, 9, 18, -15, -21]


## 8. Multiply Vectors

In [9]:
import numpy as np
array_1 = [2,4,5]
array_2 = [2,3,6]
np.multiply(array_1,array_2)

array([ 4, 12, 30])

## 9 & 10. Matrix Addition

In [10]:
# Let us create a matrix
B = np.arange(9).reshape(3,3)   # What this line of code does is that it first create a 1D array [0,1,2,3,4,5,6,7,8], and then reshape this 1D array into a 3X3 matrix.
B

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
# Create a second matrix
C = np.arange(10,27,2).reshape(3,3) # similar thing here: create a 1D array, followed by reshaping
C

array([[10, 12, 14],
       [16, 18, 20],
       [22, 24, 26]])

In [12]:
# Now let us add them up
B + C

array([[10, 13, 16],
       [19, 22, 25],
       [28, 31, 34]])

## 11. De-dup

In [13]:
t = [1, 2, 3, 1, 2, 5, 6, 7, 8]
s = []
for i in t:
    if i not in s:
        s.append(i)
s

[1, 2, 3, 5, 6, 7, 8]

## Bonus, Multiplication matrix

In [14]:
D = np.array([[1,2,5],[0,3,4]])     # This is a 2X3 matrix
E = np.array([[3,1],[2,3],[1,6]])   # This is a 3x2 matrix
np.matmul(D,E)

array([[12, 37],
       [10, 33]])